USE MagicCorp
GO

CREATE PROC EMP_OUT_PUT_PARA
@did INT,
@avg_sal INT OUTPUT
AS
SELECT @avg_sal = AVG(SALARY)
FROM EMPLOYEE
WHERE EMPLOYEE.DNO = @did
GO

DECLARE @AVG_SALY INT

EXEC EMP_OUT_PUT_PARA 30, @AVG_SALY OUTPUT

SELECT @AVG_SALY