USE MagicCorp
GO

CREATE TRIGGER NEW_EMP_SAL
ON EMPLOYEE
FOR INSERT
AS
BEGIN

PRINT('NEW_EMP_SAL trigger 가 수행')

SELECT * FROM inserted

UPDATE EMPLOYEE SET SALARY = 100
FROM inserted, EMPLOYEE
WHERE EMPLOYEE.ENO = inserted.ENO

PRINT ('NEW_EMP_SAL trigger 가 급여를 100으로 수정')

SELECT *
FROM inserted, EMPLOYEE
WHERE EMPLOYEE.ENO = inserted.ENO

END