-- MySQL Script generated by MySQL Workbench
-- Sat Jan  1 11:22:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `company` DEFAULT CHARACTER SET utf8 ;
USE `company` ;

-- -----------------------------------------------------
-- Table `company`.`부서`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`부서` (
  `부서번호` CHAR(5) NOT NULL,
  `부서이름` VARCHAR(50) NOT NULL,
  `전화번호` CHAR(20) NULL,
  `소재지` VARCHAR(100) NULL,
  PRIMARY KEY (`부서번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`사원`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`사원` (
  `사원번호` CHAR(10) NOT NULL,
  `사원이름` CHAR(10) NOT NULL,
  `전화번호` VARCHAR(45) NULL,
  `주소` VARCHAR(200) NULL,
  `생년월일` DATE NULL,
  `성별` ENUM('남', '여') NULL,
  `부서번호` CHAR(5) NOT NULL,
  PRIMARY KEY (`사원번호`),
  INDEX `fk_사원_부서1_idx` (`부서번호` ASC) VISIBLE,
  CONSTRAINT `fk_사원_부서1`
    FOREIGN KEY (`부서번호`)
    REFERENCES `company`.`부서` (`부서번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`부가정보`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`부가정보` (
  `신장` INT NULL,
  `체중` FLOAT NULL,
  `혈액형` ENUM('O', 'A', 'AB', 'B') NULL,
  `부가정보col` VARCHAR(45) NULL,
  `사원번호` CHAR(10) NOT NULL,
  PRIMARY KEY (`사원번호`),
  CONSTRAINT `fk_부가정보_사원`
    FOREIGN KEY (`사원번호`)
    REFERENCES `company`.`사원` (`사원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`부양가족`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`부양가족` (
  `가족이름` CHAR(10) NOT NULL,
  `성별` ENUM('남', '여') NULL,
  `생년월일` DATE NOT NULL,
  `관계` VARCHAR(45) NULL,
  `사원번호` CHAR(10) NOT NULL,
  PRIMARY KEY (`가족이름`, `사원번호`),
  INDEX `fk_부양가족_사원1_idx` (`사원번호` ASC) VISIBLE,
  CONSTRAINT `fk_부양가족_사원1`
    FOREIGN KEY (`사원번호`)
    REFERENCES `company`.`사원` (`사원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`프로젝트`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`프로젝트` (
  `프로젝트번호` CHAR(10) NOT NULL,
  `프로젝트명` VARCHAR(100) NULL,
  `시작일자` DATETIME NULL,
  `종료일자` DATETIME NULL,
  PRIMARY KEY (`프로젝트번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`참여내역`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`참여내역` (
  `프로젝트번호` CHAR(10) NOT NULL,
  `사원번호` CHAR(10) NOT NULL,
  `참여시작일` DATE NULL,
  `참여마감일` DATE NULL,
  PRIMARY KEY (`프로젝트번호`, `사원번호`),
  INDEX `fk_프로젝트_has_사원_사원1_idx` (`사원번호` ASC) VISIBLE,
  INDEX `fk_프로젝트_has_사원_프로젝트1_idx` (`프로젝트번호` ASC) VISIBLE,
  CONSTRAINT `fk_프로젝트_has_사원_프로젝트1`
    FOREIGN KEY (`프로젝트번호`)
    REFERENCES `company`.`프로젝트` (`프로젝트번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_프로젝트_has_사원_사원1`
    FOREIGN KEY (`사원번호`)
    REFERENCES `company`.`사원` (`사원번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
